categorias = {
    'BIOLOGIA': 'Ciencias Ambientales',
    'MAESTRÍA EN BIOLOGÍA': 'Ciencias Ambientales',
    'INGENIERIA AGROINDUSTRIAL': 'Ingenierías',
    'INGENIERIA CIVIL': 'Ingenierías',
    'INGENIERIA AGRICOLA': 'Ingenierías',
    'TECNOLOGIA EN REGENCIA DE FARMACIA': 'Tecnologías',
    'TECNOLOGIA EN ELECTRONICA INDUSTRIAL': 'Tecnologías',
    'TECNOLOGIA EN ELECTRONICA': 'Tecnologías',
    'TECNOLOGIA EN OBRAS CIVILES': 'Tecnologías',
    'TECNOLOGIA EN GESTION EMPRESARIAL': 'Tecnologías',
    'ENFERMERIA': 'Salud',
    'MEDICINA': 'Salud',
    'FONOAUDIOLOGIA': 'Salud',
    'ADMINISTRACION DE EMPRESAS': 'Administración',
    'ECONOMIA': 'Administración',
    'CONTADURIA PUBLICA': 'Administración',
    'MAESTRÍA EN ADMINISTRACIÓN DE EMPRESAS': 'Administración',
    'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN MATEMATICAS': 'Licenciaturas',
    'LICENCIATURA EN MATEMATICAS': 'Licenciaturas',
    'LICENCIATURA EN EDUCACION AMBIENTAL': 'Licenciaturas',
    'LICENCIATURA EN LENGUAS EXTRANJERAS': 'Licenciaturas',
    'LICENCIATURA EN FISICA': 'Licenciaturas',
    'MAESTRÍA EN EDUCACION': 'Maestrías',
    'MAESTRÍA EN CIENCIAS AMBIENTALES': 'Maestrías',
    'MAESTRÍA EN SALUD PUBLICA': 'Maestrías',
    'MAESTRÍA EN CIENCIAS FISICAS': 'Maestrías',
    'ESPECIALIZACIÓN EN GERENCIA DE PROYECTO': 'Especializaciones',
    'ESPECIALIZACION EN GESTION DE LA PROMOCION Y PREVENCION EN SALUD': 'Especializaciones',
    'ESPECIALIZACION EN PRODUCCÓN ANIMAL TROPICAL': 'Especializaciones',
    'ESPECIALIZACIÓN EN SEGURIDAD Y SALUD EN EL TRABAJO': 'Especializaciones',
    'ESPECIALIZACIÓN EN GERENCIA DEL TALENTO HUMANO': 'Especializaciones'
}